#!/usr/bin/env bash
# =============================================================
# goal-loop-template.sh — generator for goal-loop.sh call scaffolds.
#
# For a new metric M (coverage, a score threshold, a count, …) it emits a
# runnable loop script with goal-loop.sh's stop wiring (--goal/--check/--max/
# --state) correctly filled in, so you don't hand-write it each time — and so
# common miswirings (no --state, no cap, self-reported "done") can't happen.
#
# The generated loop never declares success itself; it defers the verdict to
# goal-loop.sh's deterministic --check exit code (no self-report).
#
# Usage:
#   goal-loop-template.sh --name <slug> --check "<deterministic cmd>" \
#       [--goal "<desc>"] [--max <N>] [--out <path>]
#     --name  : slug; determines the state file name (.goal-loop-<slug>.state) (required)
#     --check : deterministic command, exit 0 == goal met (required)
#     --goal  : one-line goal description (defaults to <slug>)
#     --max   : max attempts (default 5)
#     --out   : output path (default stdout; when set, chmod +x)
#   goal-loop-template.sh --self-test   # generate → bash -n → assert goal-loop.sh wiring
#
# Design: bash only; values are embedded with a UTF-8-safe single-quote wrapper.
# BSD/GNU grep safe.
# =============================================================
set -uo pipefail

# UTF-8-safe single-quote wrapping (bash 3.2 printf %q mangles multibyte, so do it
# by hand). In the generated script values stay single-quoted → the $(...) inside a
# CHECK is NOT expanded at assignment; goal-loop.sh's eval evaluates it later (intended).
shq() {
  printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
}

NAME=""; CHECK=""; GOAL=""; MAX=5; OUT=""; SELFTEST=0
while [ $# -gt 0 ]; do
  case "$1" in
    --name)  NAME="$2"; shift 2 ;;
    --check) CHECK="$2"; shift 2 ;;
    --goal)  GOAL="$2"; shift 2 ;;
    --max)   MAX="$2"; shift 2 ;;
    --out)   OUT="$2"; shift 2 ;;
    --self-test) SELFTEST=1; shift ;;
    *) echo "unknown arg: $1" >&2; exit 3 ;;
  esac
done

# ---- emit the scaffold to stdout (reads the vars above) ----
emit_template() {
  local slug="$NAME" check="$CHECK" goal="$GOAL" max="$MAX"
  [ -n "$goal" ] || goal="$slug"
  local state=".goal-loop-${slug}.state"

  # literal header
  cat <<'HDR'
#!/usr/bin/env bash
# =============================================================
# GENERATED by goal-loop-template.sh — a goal-directed loop wired to goal-loop.sh.
# "Done" is NOT declared here; it is decided by the deterministic --check exit code.
# =============================================================
set -uo pipefail

# Resolve goal-loop.sh relative to the repo root (works from any subdirectory).
REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
GOAL_LOOP="$REPO_ROOT/scripts/goal-loop.sh"
HDR

  # dynamic vars (single-quoted for embedding safety)
  printf 'GOAL=%s\n'  "$(shq "$goal")"
  printf 'CHECK=%s\n' "$(shq "$check")"
  printf 'MAX=%s\n'   "$(shq "$max")"
  printf 'STATE="$REPO_ROOT/%s"\n' "$state"

  # literal footer
  cat <<'HDR'

# 1) reset the counter once when starting a new goal
"$GOAL_LOOP" --reset --state "$STATE"

# 2) loop body: call goal-loop at the top of each iteration and branch on exit code
#    exit 0 = ✅ GOAL MET / 1 = 🔁 CONTINUE / 2 = 🛑 CAP REACHED
while : ; do
  "$GOAL_LOOP" --goal "$GOAL" --check "$CHECK" --max "$MAX" --state "$STATE"
  rc=$?
  case "$rc" in
    0)
      echo "✅ GOAL MET — commit/PR the result; consider pinning --check into CI as a floor"
      exit 0 ;;
    1)
      # TODO: implement ONE iteration of work that moves --check forward here
      #       (add a test, fix the implementation, load data, …). Left as a
      #       placeholder, nothing progresses and the loop hits CAP after MAX tries.
      echo "🔁 CONTINUE — do one iteration of work, then loop"
      continue ;;
    2)
      echo "🛑 CAP REACHED — stop and escalate to a human; record the unmet goal wherever you track blockers"
      exit 2 ;;
    *)
      echo "goal-loop.sh unexpected exit: $rc" >&2
      exit "$rc" ;;
  esac
done
HDR
}

# ---- self-test: generate → syntax check → assert goal-loop.sh wiring (hermetic) ----
if [ "$SELFTEST" = "1" ]; then
  tmp="$(mktemp "${TMPDIR:-/tmp}/goal-loop-tmpl.XXXXXX")"
  trap 'rm -f "$tmp"' EXIT
  # generate with sample args (a check containing single quotes / spaces also proves embedding)
  NAME="selftest-metric"; GOAL="raise a sample metric to a threshold"
  CHECK='test "$(printf 91)" -ge 90'; MAX=3; OUT=""
  emit_template > "$tmp" || { echo "self-test: generation failed" >&2; exit 1; }

  # (1) generated script is valid bash
  if ! bash -n "$tmp"; then
    echo "self-test: ❌ bash -n (syntax) failed" >&2; exit 1
  fi
  # (2) generated script references scripts/goal-loop.sh
  if ! grep -q "scripts/goal-loop.sh" "$tmp"; then
    echo "self-test: ❌ generated script does not reference scripts/goal-loop.sh" >&2; exit 1
  fi
  # (3) stop wiring (--reset / --check / --max / --state) is all present
  miss=0
  for f in "\-\-reset" "\-\-check" "\-\-max" "\-\-state" ; do
    grep -qE "$f" "$tmp" || { echo "self-test: ❌ stop wiring $f missing" >&2; miss=1; }
  done
  [ "$miss" -eq 0 ] || exit 1

  echo "✅ self-test PASS: generate → bash -n → goal-loop.sh ref → stop wiring (--reset/--check/--max/--state) OK"
  exit 0
fi

# ---- normal mode: generate ----
[ -n "$NAME" ]  || { echo "goal-loop-template: --name <slug> is required" >&2; exit 3; }
# The slug is interpolated into the generated STATE path, so restrict it to a safe
# charset — this closes a command-injection path (e.g. --name 'x$(...)y') and also
# prevents silently-broken generation for names with spaces/quotes.
case "$NAME" in
  *[!A-Za-z0-9._-]*|'') echo "goal-loop-template: --name must match [A-Za-z0-9._-]+ (got: '$NAME')" >&2; exit 3 ;;
esac
[ -n "$CHECK" ] || { echo "goal-loop-template: --check <cmd> is required" >&2; exit 3; }

if [ -n "$OUT" ]; then
  emit_template > "$OUT"
  chmod +x "$OUT"
  echo "generated: $OUT (state=.goal-loop-${NAME}.state; chmod +x)" >&2
else
  emit_template
fi
